<?php
    // @codingStandardsIgnoreFile

    /** @var \Magento\Store\Block\Switcher $block */
    if (count($block->getStores()) < 1) {
        return;
    }

    $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : '';
    $currentStore = is_array($block->getStores()) ? $block->getStores()[$block->getCurrentStoreId()] : null;
    $flagRenderer = $block->getChildBlock('easyflags.renderer');
    $helper = $this->helper('Swissup\Easyflags\Helper\Data');
?>
<div class="easyflags switcher language switcher-language" data-ui-id="language-switcher" id="switcher-language<?php /* @escapeNotVerified */ echo $id?>">
    <div class="actions <?= $helper->getLanguageSwitcherMode() ?>-mode options switcher-options">

    <?php if ($helper->getLanguageSwitcherMode() == \Swissup\Easyflags\Model\Config\Source\Mode::ONELINE): ?>
        <?php /* ONELINE MODE */ ?>
        <!-- Active option -->
        <div class="easyflags-active">
            <strong class="view-<?= $block->escapeHtml($block->getCurrentStoreCode()) ?>" title="<?= $block->escapeHtml($block->getStoreName()) ?>">
                <?= $flagRenderer->setStore($currentStore)->toHtml() ?>
            </strong>
        </div>

        <!-- Clickable options -->
        <div class="easyflags-clickable-options" >
            <?php foreach ($block->getStores() as $_lang): ?>
                <?php if ($_lang->getId() != $block->getCurrentStoreId()): ?>
                    <a href="#" data-post='<?= /* @escapeNotVerified */ $block->getTargetStorePostData($_lang); ?>' title="<?= $block->escapeHtml($_lang->getName()) ?>">
                        <?= $flagRenderer->setStore($_lang)->toHtml() ?>
                    </a>
                <?php endif; ?>
            <?php endforeach; ?>
        </div>

    <?php elseif ($helper->getLanguageSwitcherMode() == \Swissup\Easyflags\Model\Config\Source\Mode::DROPDOWN): ?>
        <?php /* DROPDOWN MODE */ ?>
        <div class="action toggle switcher-trigger"
             data-mage-init='{"dropdown":{}}'
             data-toggle="dropdown"
             data-trigger-keypress-button="true">
            <strong class="view-<?= $block->escapeHtml($block->getCurrentStoreCode()) ?>">
                <?= $flagRenderer->setStore($currentStore)->toHtml() ?>
                <span class="flag-title"><?= $block->escapeHtml($block->getStoreName()) ?></span>
            </strong>
        </div>
        <ul class="dropdown switcher-dropdown"
            data-target="dropdown">
            <?php foreach ($block->getStores() as $_lang): ?>
                <?php if ($_lang->getId() != $block->getCurrentStoreId()): ?>
                    <li class="view-<?= $block->escapeHtml($_lang->getCode()) ?> switcher-option">
                        <a href="#" data-post='<?= /* @noEscape */ $block->getTargetStorePostData($_lang) ?>'>
                            <?= $flagRenderer->setStore($_lang)->toHtml() ?>
                            <span class="flag-title"><?= $block->escapeHtml($_lang->getName()) ?></span>
                        </a>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>
    <?php elseif ($helper->getLanguageSwitcherMode() == \Swissup\Easyflags\Model\Config\Source\Mode::POPUP): ?>
        <?php /* MODAL POPUP MODE */ ?>
        <div class="action toggle switcher-trigger" data-bind="click: function(){ var modal = jQuery('.easyflags .switcher-popup').data('mageModal'); if (modal) modal.openModal(); }">
            <strong class="view-<?= $block->escapeHtml($block->getCurrentStoreCode()) ?>">
                <?= $flagRenderer->setStore($currentStore)->toHtml() ?>
                <span class="flag-title"><?= $block->escapeHtml($block->getStoreName()) ?></span>
            </strong>
        </div>
        <div class="switcher-popup" data-mage-init='{"Magento_Ui/js/modal/modal":{"responsive": true, "modalClass": "easyflags", "buttons":[]}}'>
            <div class="easyflags-clickable-options" >
                <?php foreach ($block->getStores() as $_lang): ?>
                    <?php if ($_lang->getId() != $block->getCurrentStoreId()): ?>
                        <a href="#" data-post='<?= /* @escapeNotVerified */ $block->getTargetStorePostData($_lang); ?>' title="<?= $block->escapeHtml($_lang->getName()) ?>">
                            <?= $flagRenderer->setStore($_lang)->toHtml() ?>
                            <span class="flag-title"><?= $block->escapeHtml($_lang->getName()) ?></span>
                        </a>
                    <?php endif; ?>
                <?php endforeach; ?>
            </div>
        </div>
    <?php endif ?>
    </div>

</div>
