<?php
    // @codingStandardsIgnoreFile
    use Swissup\Easyflags\Model\Config\Source\Mode as SwitcherMode;

    /** @var \Magento\Store\Block\Switcher $block */
    if (count($block->getStores()) < 1) {
        return;
    }

    $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : '';
    $currentStore = is_array($block->getStores()) ? $block->getStores()[$block->getCurrentStoreId()] : null;
    $flagRenderer = $this->getLayout()->getBlock('easyflags.renderer');
    $switcherMode = $this->helper('Swissup\Easyflags\Helper\Data')->getLanguageSwitcherMode();
?>
<div class="easyflags switcher language switcher-language" data-ui-id="language-switcher" id="switcher-language<?php /* @escapeNotVerified */ echo $id?>" data-mage-init='{"Swissup_Easyflags/js/store-switcher":{}}'>
    <div class="actions <?= $switcherMode ?> options switcher-options">

    <?php if ($switcherMode == SwitcherMode::ONELINE): ?>
        <?php /* ONELINE MODE */ ?>
        <!-- Active option -->
        <div class="easyflags-active">
            <strong class="view-<?= $block->escapeHtml($block->getCurrentStoreCode()) ?>" title="<?= $block->escapeHtml($block->getStoreName()) ?>" data-store-code="<?= $block->escapeHtml($currentStore->getCode()) ?>">
                <?= $flagRenderer->setStore($currentStore)->toHtml() ?>
            </strong>
        </div>

        <!-- Clickable options -->
        <div class="easyflags-clickable-options" >
            <?php foreach ($block->getStores() as $_lang): ?>
                <?php if ($_lang->getId() != $block->getCurrentStoreId()): ?>
                    <a href="#" title="<?= $block->escapeHtml($_lang->getName()) ?>" data-store-code="<?= $block->escapeHtml($_lang->getCode()) ?>">
                        <?= $flagRenderer->setStore($_lang)->toHtml() ?>
                    </a>
                <?php endif; ?>
            <?php endforeach; ?>
        </div>

    <?php elseif ($switcherMode == SwitcherMode::DROPDOWN): ?>
        <?php /* DROPDOWN MODE */ ?>
        <div class="action toggle switcher-trigger"
             data-mage-init='{"dropdown":{}}'
             data-toggle="dropdown"
             data-trigger-keypress-button="true">
            <strong class="view-<?= $block->escapeHtml($block->getCurrentStoreCode()) ?>" data-store-code="<?= $block->escapeHtml($currentStore->getCode()) ?>">
                <?= $flagRenderer->setStore($currentStore)->toHtml() ?>
                <span class="flag-title"><?= $block->escapeHtml($block->getStoreName()) ?></span>
            </strong>
        </div>
        <ul class="dropdown switcher-dropdown"
            data-target="dropdown">
            <?php foreach ($block->getStores() as $_lang): ?>
                <?php if ($_lang->getId() != $block->getCurrentStoreId()): ?>
                    <li class="view-<?= $block->escapeHtml($_lang->getCode()) ?> switcher-option">
                        <a href="#" data-store-code="<?= $block->escapeHtml($_lang->getCode()) ?>">
                            <?= $flagRenderer->setStore($_lang)->toHtml() ?>
                            <span class="flag-title"><?= $block->escapeHtml($_lang->getName()) ?></span>
                        </a>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>
    <?php elseif ($switcherMode == SwitcherMode::POPUP): ?>
        <?php /* MODAL POPUP MODE */ ?>
        <div class="action toggle switcher-trigger">
            <strong class="view-<?= $block->escapeHtml($block->getCurrentStoreCode()) ?>" data-store-code="<?= $block->escapeHtml($currentStore->getCode()) ?>">
                <?= $flagRenderer->setStore($currentStore)->toHtml() ?>
                <span class="flag-title"><?= $block->escapeHtml($block->getStoreName()) ?></span>
            </strong>
        </div>
        <div class="switcher-popup" data-mage-init='{"Magento_Ui/js/modal/modal":{"responsive": true, "modalClass": "easyflags", "buttons":[]}}'>
            <div class="easyflags-clickable-options" >
                <?php foreach ($block->getStores() as $_lang): ?>
                    <?php if ($_lang->getId() != $block->getCurrentStoreId()): ?>
                        <a href="#" title="<?= $block->escapeHtml($_lang->getName()) ?>" data-store-code="<?= $block->escapeHtml($_lang->getCode()) ?>">
                            <?= $flagRenderer->setStore($_lang)->toHtml() ?>
                            <span class="flag-title"><?= $block->escapeHtml($_lang->getName()) ?></span>
                        </a>
                    <?php endif; ?>
                <?php endforeach; ?>
            </div>
        </div>
    <?php endif ?>
    </div>

</div>
