<?php
    // @codingStandardsIgnoreFile

    /** @var \Magento\Store\Block\Switcher $block */
    if (count($block->getStores()) < 1) {
        return;
    }

    $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : '';
    $helper = $this->helper('Swissup\Easyflags\Helper\Data');
?>
<div class="easyflags inline-mode switcher language switcher-language" data-ui-id="language-switcher" id="switcher-language<?php /* @escapeNotVerified */ echo $id?>">
    <div class="actions options switcher-options">

        <!-- Active option -->
        <div class="easyflags-active" id="switcher-language-trigger<?php /* @escapeNotVerified */ echo $id?>">
            <strong class="view-<?= $block->escapeHtml($block->getCurrentStoreCode()) ?>" title="<?= $block->escapeHtml($block->getStoreName()) ?>">
                <?php if ($imageUrl = $helper->getImageUrl($block->getCurrentStoreId())): ?>
                    <img src="<?= $imageUrl ?>"/>
                <?php else: ?>
                    <span><?= substr($block->getStoreName(), 0, 3) ?></span>
                <?php endif; ?>
            </strong>
        </div>

        <!-- Clickable options -->
        <div class="easyflags-clickable-options" >
            <?php foreach ($block->getStores() as $_lang): ?>
                <?php if ($_lang->getId() != $block->getCurrentStoreId()): ?>
                    <a href="#" data-post='<?= /* @escapeNotVerified */ $block->getTargetStorePostData($_lang); ?>' title="<?= $block->escapeHtml($_lang->getName()) ?>">
                    <?php if ($imageUrl = $helper->getImageUrl($_lang->getId())): ?>
                        <img src="<?= $imageUrl ?>"/>
                    <?php else: ?>
                        <span><?= substr($_lang->getName(), 0, 3) ?></span>
                    <?php endif; ?>
                    </a>
                <?php endif; ?>
            <?php endforeach; ?>
        </div>
    </div>
</div>
