<?php
    $helper = $this->helper('Swissup\Easyflags\Helper\Data');
    if (!$store = $block->getStore()) {
        return;
    }
?>
<?php if ($imageUrl = $helper->getImageUrl($store->getId())): ?>
    <img class="flag-image" src="<?= $imageUrl ?>" alt="<?= $block->escapeHtml($store->getName()) ?>" />
<?php elseif ($block->getShowPlaceholder()): ?>
    <span class="flag-placeholder"><?= strtoupper(mb_substr($store->getName(), 0, 3)) ?></span>
<?php endif; ?>
